title: Venkata Sarath Chitta
description: >-
  Principal Software Engineer & Distributed Systems Architect
  â€” 20+ years building ultra-scalable, low-latency, cloud-native systems and AI-powered platforms.
url: "https://sarath-hotspot.github.io"
baseurl: ""
show_downloads: false

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Author
author:
  name: Venkata Sarath Chitta
  email: sarath.chitta@gmail.com
  location: Seattle, WA, USA